version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Laurinda2002
      POSTGRES_DB: CursoEstudanteDB
    ports:
      - "5433:5432" # Porta externa do host -> interna do container
    volumes:
      - pgdata:/var/lib/postgresql/data

  webapi:
    build: .
    container_name: aspnetapi_container
    depends_on:
      - db
    ports:
      - "8080:8080" # Porta correta mapeada
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=CursoEstudanteDB;Username=postgres;Password=Laurinda2002

volumes:
  pgdata:

